In [1]:
import numpy as np


In [2]:
#XOR 연산의 x1, x2 입력을 저장하는 배열
X = np.array([
	[0., 0.],
	[0., 1.],
	[1., 0.],
	[1., 1]
], dtype="float32")

In [3]:
#XOR 연산의 y 출력을 저장하는 배열
y = np.array([
	[0.],
	[1.],
	[1.],
	[0.]
], dtype="float32")

In [4]:
#X에 곱해지는 값 선언
w = np.array([[1], [2]], dtype="float32")

In [5]:
#X에 더해지는 값 선언
b = np.array([3], dtype="float32")

In [6]:
#X에 w를 곱하고 b를 더한 예측값을 hypothesis에 대입
hypothesis = np.dot(X, w) + b
hypothesis

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [7]:
#h를 0 ~ 1 사이 범위로 변경하는 활성함수 선언
def sigmoid(h):
	return 1 / (1 + np.exp(-h))

In [8]:
#활성함수를 이용하여 hypothesis의 범위를 0 ~ 1 사이로 변경
hypothesis = sigmoid(np.dot(X, w) + b)
hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [9]:
#예측값 - 실제값
(hypothesis - y)

array([[ 0.95257413],
       [-0.00669283],
       [-0.01798624],
       [ 0.9975274 ]], dtype=float32)

In [10]:
#X의 줄칸을 반대로 전환하고 0번째 줄을 리턴
X.T
X.T[0]

array([0., 0., 1., 1.], dtype=float32)

In [11]:
#2차원 배열인 (hypothesis - y)와 변환하기 위해 X.T[0]를 2차원 배열로 변환
X_col_2d1 = X.T[0].reshape(1, -1)
X_col_2d1

array([[0., 0., 1., 1.]], dtype=float32)

In [12]:
#w1의 수정값
w1_gred = 1 / 4 * np.sum(np.dot(X_col_2d1, (hypothesis - y)))
print("w_gred:", w1_gred)

w_gred: 0.24488529562950134


In [13]:
#X의 줄칸을 반대로 전환하고 1번째 줄을 리턴
X.T[1]

array([0., 1., 0., 1.], dtype=float32)

In [14]:
#2차원 배열인 (hypothesis - y)와 변환하기 위해 X.T[1]를 2차원 배열로 변환
X_col_2d2 = X.T[1].reshape(1, -1)

In [15]:
#w2의 수정값
w2_gred = 1 / 4 * np.sum(np.dot((hypothesis - y), X_col_2d2))
print("w_gred:", w2_gred)

w_gred: 0.9627112150192261


In [17]:
#b의 수정값
b_gred = 1 / 4 * np.sum(hypothesis - y)
print("b_gred:", b_gred)

b_gred: 0.48135560750961304


In [18]:
#1000번 반복해서 오차 제곱의 합이 0으로 수렴되는 w, b를 찾음
learning_rate = 0.1

for i in range(1000):
    for j in range(2):
        #예측값을 hypothesis에 대입
        hypothesis = sigmoid(np.dot(X, w) + b)
        print("hypothesis:", hypothesis)

        #오차 계산
        cost = -1 / 4 * (y * np.log(hypothesis) + ( 1 - y) * np.log(1 - hypothesis))
        print("cost:", cost)

        #X의 줄칸을 변경하여 j번째 칸을 2차원 배열로 생성
        X_col_2d = X.T[j].reshape(1, -1)

        #w, b의 기울기를 계산하고 업데이트
        w_gred = 1 / 4 * np.sum(np.dot(X_col_2d, (hypothesis - y)))
        print("w_{}gred: {}".format(i, w_gred))
        w[j] = w[j] - learning_rate * w_gred
        print("w{} : {}".format(j, w))

        b_gred = 1 / 4 * np.sum(hypothesis - y)
        print("b{}_gred: {}".format(i, b_gred))
        b = b - learning_rate * b_gred
        print("b : {}".format(b))

hypothesis: [[0.95257413]
 [0.9933072 ]
 [0.98201376]
 [0.9975274 ]]
cost: [[0.7621469 ]
 [0.00167883]
 [0.00453749]
 [1.5006233 ]]
w_0gred: 0.24488529562950134
w0 : [[0.9755115]
 [2.       ]]
b0_gred: 0.48135560750961304
b : [2.9518645]
hypothesis: [[0.9503516 ]
 [0.99297947]
 [0.9806851 ]
 [0.9973416 ]]
cost: [[0.75069726]
 [0.00176132]
 [0.00487596]
 [1.4825052 ]]
w_0gred: 0.24758026003837585
w1 : [[0.9755115]
 [1.975242 ]]
b0_gred: 0.4803394377231598
b : [2.9038305]
hypothesis: [[0.9480354]
 [0.9924534]
 [0.9797539]
 [0.9971414]]
cost: [[0.7392982 ]
 [0.00189381]
 [0.00511346]
 [1.4643576 ]]
w_1gred: 0.24422383308410645
w0 : [[0.9510891]
 [1.975242 ]]
b1_gred: 0.47934603691101074
b : [2.855896]
hypothesis: [[0.9456226 ]
 [0.99208564]
 [0.9782678 ]
 [0.9969277 ]]
cost: [[0.72795177]
 [0.00198646]
 [0.00549296]
 [1.4463304 ]]
w_1gred: 0.24725332856178284
w1 : [[0.9510891]
 [1.9505167]]
b1_gred: 0.4782259464263916
b : [2.8080735]
hypothesis: [[0.9431105 ]
 [0.99149525]
 [0.9772274 ]
 

In [19]:
w

array([[0.00348961],
       [0.00570618]], dtype=float32)

In [20]:
b

array([-0.00509937], dtype=float32)

In [21]:
#X에 w를 곱하고 b를 더한 후 활성함수를 이용하여 데이터의 범위를 0 ~ 1로 설정
predict = sigmoid(np.dot(X, w) + b)
predict

array([[0.49872515],
       [0.5001517 ],
       [0.49959758],
       [0.5010241 ]], dtype=float32)

In [22]:
#predict에 저장된 값이 0.5 초과면 1, 아니면 0 리턴
predict01 = np.where(predict > 0.5, 1, 0)
print("=" * 100)
print("predict01")
print(predict01)

predict01
[[0]
 [1]
 [0]
 [1]]


In [23]:
#predict01과 y가 같으면 true, 다르면 false 리턴
predict02 = (predict01 == y)
predict02

array([[ True],
       [ True],
       [False],
       [False]])

In [24]:
#true는 1로, false는 0으로 변환하여 합을 계산한 뒤 정확도를 계산
acc = np.sum(predict02) / 4
acc

0.5

In [ ]:
#간단한 XOR 연산의 정확도가 0.5밖에 되지 않음 => XOR은 선형분리로 풀지 못하는 문제이기 때문
#입력 차원을 늘리거나 입력을 비선형 변환하여 선형분리가 가능하도록 해야 함
#다층 퍼셉트론을 이용하여 입력을 늘리고 여러개의 선으로 분리
#오차 역전파로 가중치를 업데이트