In [1]:
import numpy as np

In [5]:
#AND 연산의 x1, x2 입력을 저장하는 배열
X = np.array([
        [0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]
    ], dtype = "float32")

In [6]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [7]:
#AND 연산의 y출력을 저장하는 배열
y = np.array([
        [0.],
        [0.],
        [0.],
        [1.]
    ], dtype = "float32")

In [8]:
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [9]:
#X에 곱해지는 값 선언
w = np.array([[1], [2]], dtype = "float32")

#X에 더해지는 값 선언
b = np.array([3], dtype = "float32")

In [10]:
w

array([[1.],
       [2.]], dtype=float32)

In [11]:
b

array([3.], dtype=float32)

In [12]:
#X에 w를 곱하기
np.dot(X, w)

array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)

In [13]:
#X에 w를 곱하고 b를 더하기
np.dot(X, w) + b

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [14]:
#h를 0 ~ 1 사이 범위로 변경하는 활성함수 선언
def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [15]:
#X * w + b를 실행해서 예측값을 hypothesis에 대입
hypothesis = np.dot(X, w) + b
hypothesis

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [16]:
#hypothesis를 활성함수를 이용하여 값의 범위를 0 ~ 1 사이로 변경
hypothesis = sigmoid(np.dot(X, w) + b)
hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [17]:
#예측값 - 실제값
(hypothesis - y)

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [18]:
#X의 줄칸을 반대로 전환
X.T

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [19]:
#반대로 전환한 X의 0번째 줄을 리턴
X.T[0]

array([0., 0., 1., 1.], dtype=float32)

In [20]:
#이차원 배열인 (hypothesis - y)와 변환하기 위해
#X.T[0]을 2차원 배열로 변환
X_col_2d1 = X.T[0].reshape(1, -1)
X_col_2d1

array([[0., 0., 1., 1.]], dtype=float32)

In [21]:
#w1의 수정값
w1_gred = 1 / 4 * sum(np.dot(X_col_2d1, (hypothesis - y)))
print("w_gred:", w1_gred)

w_gred: [0.2448853]


In [22]:
#반대로 전환한 X의 1번째 줄을 리턴
X.T[1]

array([0., 1., 0., 1.], dtype=float32)

In [23]:
#이차원 배열인 (hypothesis - y)와 변환하기 위해
#X.T[1]을 2차원 배열로 변환
X_col_2d2 = X.T[1].reshape(1, -1)
X_col_2d2

array([[0., 1., 0., 1.]], dtype=float32)

In [24]:
#w2의 수정값
w2_gred = 1 / 4 * np.sum(np.dot(X_col_2d2, (hypothesis - y)))
print("w_gred:", w2_gred)

w_gred: 0.24770864844322205


In [25]:
#b의 수정값
b_gred = 1 / 4 * np.sum(hypothesis - y)
print("b_gred:", b_gred)

b_gred: 0.731355607509613


In [26]:
#learning rate
learning_rate = 0.1

#1000번 반복해서 오차 제곱의 합이 0으로 수렴되는 w와 b를 찾음
for i in range(1000):
    for j in range(2):
        #예측값을 hypothesis에 대입
        hypothesis = sigmoid(np.dot(X, w) + b)
        print("hypothesis:", hypothesis)
        #오차를 계산
        cost = -1 / 4 * (y * np.log(hypothesis) + (1 - y) * np.log(1 - hypothesis))
        print("cost:", cost)
        #X의 줄칸을 변경하여 j번째 칸을 2차원 배열로 생성
        X_col_2d = X.T[j].reshape(1, -1)
        #w의 기울기 계산
        w_gred = 1 / 4 * np.sum(np.dot(X_col_2d, (hypothesis - y)))
        print("w_{}gred:{}".format(i, w_gred))
        #w 업데이트
        w[j] = w[j] - learning_rate * w_gred
        print("w{}:{}".format(j, w))
        #b의 기울기 계산
        b_gred = 1 / 4 * np.sum(hypothesis - y)
        print("b{}_gred:{}".format(i, b_gred))
        #b 업데이트
        b = b - learning_rate * b_gred
        print("b:{}".format(b))

hypothesis: [[0.95257413]
 [0.9933072 ]
 [0.98201376]
 [0.9975274 ]]
cost: [[7.6214689e-01]
 [1.2516798e+00]
 [1.0045371e+00]
 [6.1891036e-04]]
w_0gred:0.24488529562950134
w0:[[0.9755115]
 [2.       ]]
b0_gred:0.731355607509613
b:[2.9268644]
hypothesis: [[0.94915855]
 [0.9928029 ]
 [0.9802059 ]
 [0.99727446]]
cost: [[7.4476081e-01]
 [1.2335199e+00]
 [9.8059279e-01]
 [6.8231573e-04]]
w_0gred:0.2475193440914154
w1:[[0.9755115]
 [1.9752481]]
b0_gred:0.7298604249954224
b:[2.8538783]
hypothesis: [[0.94551885]
 [0.9920699 ]
 [0.97873896]
 [0.99699557]]
cost: [[7.2747511e-01]
 [1.2092724e+00]
 [9.6271980e-01]
 [7.5223856e-04]]
w_1gred:0.24393363296985626
w0:[[0.9511181]
 [1.9752481]]
b1_gred:0.7283308506011963
b:[2.7810452]
hypothesis: [[0.94164294]
 [0.99147594]
 [0.9766187 ]
 [0.9966897 ]]
cost: [[7.1029371e-01]
 [1.1912156e+00]
 [9.3895477e-01]
 [8.2895352e-04]]
w_1gred:0.24704140424728394
w1:[[0.9511181]
 [1.950544 ]]
b1_gred:0.7266068458557129
b:[2.7083845]
hypothesis: [[0.93751955]
 [0.

In [28]:
#Gradient Decent로 계산한 w
w

array([[3.5944269],
       [3.6230009]], dtype=float32)

In [29]:
#Gradient Decent로 계산한 b
b

array([-5.6846833], dtype=float32)

In [30]:
#X에 w를 곱하고 b를 더함
np.dot(X, w) + b

array([[-5.6846833],
       [-2.0616825],
       [-2.0902565],
       [ 1.5327444]], dtype=float32)

In [31]:
#활성함수를 이용하여 데이터의 범위를 0 ~ 1로 설정
predict = sigmoid(np.dot(X, w) + b)
predict

array([[0.0033861 ],
       [0.11287726],
       [0.11004746],
       [0.8224075 ]], dtype=float32)

In [32]:
#True를 정수로 변환(1)
int(True)

#False를 정수로 변환(0)
int(False)

0

In [33]:
#np.where(조건, 조건만족시 리턴값, 거짓일때 리턴값)
#predict에 저장된 값이 0.5 초과일 시 1 리턴, 아니면 0 리턴
predict01 = np.where(predict >= 0.5, 1, 0)
print("=" * 100)
print("predict01")
print(predict01)

predict01
[[0]
 [0]
 [0]
 [1]]


In [34]:
#predict01 == y가 같으면 True, 다르면 False 리턴
predict02 = (predict01 == y)
predict02

array([[ True],
       [ True],
       [ True],
       [ True]])

In [35]:
#True는 1로, False는 0으로 변환하여 합을 계산
np.sum(predict02)

4

In [36]:
#정확도 계산
acc = np.sum(predict02) / 4
acc

1.0

In [37]:
#0, 1의 and 연산 실행
arr = np.array([[0, 1]], dtype = "float32")
#sigmoid(arr * w + b)를 계산
predict = sigmoid(np.dot(arr, w) + b)
predict

array([[0.11287726]], dtype=float32)

In [38]:
#predict에 저장된 값이 0.5 초과일 시 1 리턴, 아니면 0 리턴
predict01 = np.where(predict >= 0.5, 1, 0)
print("=" * 100)
print("predict01")
print(predict01)

predict01
[[0]]


In [39]:
#1, 1의 and 연산 실행
arr = np.array([[1, 1]], dtype = "float32")
#sigmoid(arr * w + b)를 계산
predict = sigmoid(np.dot(arr, w) + b)
predict

array([[0.8224075]], dtype=float32)

In [40]:
#predict에 저장된 값이 0.5 초과일 시 1 리턴, 아니면 0 리턴
predict01 = np.where(predict >= 0.5, 1, 0)
print("=" * 100)
print("predict01")
print(predict01)

predict01
[[1]]
