In [1]:
import torch
import torch.optim as optim
import numpy as np

In [2]:
#AND 연산의 x1, x2를 저장하는 배열
X = torch.FloatTensor([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

In [3]:
#AND 연산의 y출력을 저장하는 배열
y = torch.FloatTensor([
        [0],
        [0],
        [0],
        [1]
    ])

In [4]:
X

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [5]:
y

tensor([[0.],
        [0.],
        [0.],
        [1.]])

In [6]:
#w에 곱해지는 값을 1, 2로 초기화
#학습을 통해 값이 변경되는 변수임을 명시(requires_grad = True)
w = torch.tensor([[1.0], [2.0]], requires_grad = True)

In [7]:
w

tensor([[1.],
        [2.]], requires_grad=True)

In [8]:
#b에 더해지는 값을 3으로 초기화
#학습을 통해 값이 변경되는 변수임을 명시(requires_grad = True)
b = torch.tensor([3.0], requires_grad = True)

In [9]:
b

tensor([3.], requires_grad=True)

In [11]:
#배열 X와 w를 곱하고 b를 더함
torch.matmul(X, w) + b

tensor([[3.],
        [5.],
        [4.],
        [6.]], grad_fn=<AddBackward0>)

In [12]:
#배열 X와 w를 곱한 뒤 b를 더한 값의 sigmoid 계산
torch.sigmoid(torch.matmul(X, w) + b)

tensor([[0.9526],
        [0.9933],
        [0.9820],
        [0.9975]], grad_fn=<SigmoidBackward0>)

In [13]:
#optim.Adam([w, b] : 미분을 자동 계산하여 w, b를 수정할 객체 생성
# lr = 0.01 : learning_rate를 0.01로 설정
optimizer = optim.Adam([w, b], lr = 0.01)
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)

In [15]:
#5000번 반복하여 오차가 0으로 수렴하는 w, b를 찾음
for i in range(5000):
    print("i=", i)
    print("w=", w)
    print("b=", b)

    #예측값을 hypothesis에 대입
    hypothesis = torch.sigmoid(torch.matmul(X, w) + b)
    print("hypothesis=", hypothesis)

    #오차를 계산해서 cost에 저장
    cost = torch.mean(-y * torch.log(hypothesis) - (1 - y) * torch.log(1 - hypothesis))
    print("cost=", cost)

    #cost를 이용하여 미분을 계산하고 w, b 업데이트
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    print("=" * 100)

i= 0
w= tensor([[1.],
        [2.]], requires_grad=True)
b= tensor([3.], requires_grad=True)
hypothesis= tensor([[0.9526],
        [0.9933],
        [0.9820],
        [0.9975]], grad_fn=<SigmoidBackward0>)
cost= tensor(3.0190, grad_fn=<MeanBackward0>)
i= 1
w= tensor([[0.9900],
        [1.9900]], requires_grad=True)
b= tensor([2.9900], requires_grad=True)
hypothesis= tensor([[0.9521],
        [0.9932],
        [0.9817],
        [0.9975]], grad_fn=<SigmoidBackward0>)
cost= tensor(3.0067, grad_fn=<MeanBackward0>)
i= 2
w= tensor([[0.9800],
        [1.9800]], requires_grad=True)
b= tensor([2.9800], requires_grad=True)
hypothesis= tensor([[0.9517],
        [0.9930],
        [0.9813],
        [0.9974]], grad_fn=<SigmoidBackward0>)
cost= tensor(2.9945, grad_fn=<MeanBackward0>)
i= 3
w= tensor([[0.9700],
        [1.9700]], requires_grad=True)
b= tensor([2.9700], requires_grad=True)
hypothesis= tensor([[0.9512],
        [0.9929],
        [0.9809],
        [0.9973]], grad_fn=<SigmoidBackward0>)
co

In [16]:
#오차가 0으로 수렴하는 w값(초기값은 1, 2였음)
w

tensor([[7.0477],
        [7.0392]], requires_grad=True)

In [17]:
#오차가 0으로 수렴하는 b값(초기값은 3이었음)
b

tensor([-10.6366], requires_grad=True)

In [18]:
torch.sigmoid(torch.matmul(X, w) + b)

tensor([[2.4019e-05],
        [2.6663e-02],
        [2.6886e-02],
        [9.6924e-01]], grad_fn=<SigmoidBackward0>)

In [19]:
predict = torch.sigmoid(torch.matmul(X, w) + b)
predict

tensor([[2.4019e-05],
        [2.6663e-02],
        [2.6886e-02],
        [9.6924e-01]], grad_fn=<SigmoidBackward0>)

In [20]:
#predict를 numpy 배열로 변환
predict.detach().numpy()

array([[2.4019317e-05],
       [2.6663482e-02],
       [2.6886106e-02],
       [9.6924007e-01]], dtype=float32)

In [22]:
#predict에 저장된 값이 0.5 초과이면 1, 아니면 0 리턴
predict01 = np.where(predict.detach().numpy() >= 0.5, 1, 0)
predict01

array([[0],
       [0],
       [0],
       [1]])

In [24]:
#y를 numpy 배열로 변환
#predict01과 y가 같으면 True, 다르면 False 리턴
predict02 = predict01 == (y.detach().numpy())
predict02

array([[ True],
       [ True],
       [ True],
       [ True]])

In [25]:
#True는 1, False는 0으로 합을 계산
np.sum(predict02)

4

In [26]:
#정확도 계산
np.sum(predict02) / 4

1.0

In [27]:
#0, 1의 AND 연산 실행
arr = torch.FloatTensor([
        [0, 1]
    ])

predict = torch.sigmoid(torch.matmul(arr, w) + b)
predict

tensor([[0.0267]], grad_fn=<SigmoidBackward0>)

In [28]:
#predict에 저장된 값이 0.5 이상이면 1, 아니면 0 리턴
torch.where(predict > 0.5, 1, 0)

tensor([[0]])

In [29]:
#1, 1의 AND 연산 실행
arr = torch.FloatTensor([
        [1, 1]
    ])

predict = torch.sigmoid(torch.matmul(arr, w) + b)
predict

tensor([[0.9692]], grad_fn=<SigmoidBackward0>)

In [30]:
#predict에 저장된 값이 0.5 이상이면 1, 아니면 0 리턴
torch.where(predict > 0.5, 1, 0)

tensor([[1]])