In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np

In [4]:
#AND 연산의 x1, x2 입력을 저장하는 배열
X = np.array([
                [0., 0],
                [0., 1.],
                [1., 0.],
                [1., 1.]
    ], dtype = "float32")

In [5]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [6]:
#AND 연산의 y 출력을 저장하는 배열
y = np.array([0, 0, 0, 1], dtype = "int32")

In [7]:
y

array([0, 0, 0, 1])

In [8]:
#입력값을 읽어서 예측할 Sequential 객체 생성
model = Sequential()

#model에 데이터 분석 객체 추가

#Dense: 선형 회귀를 수행할 객체
#Dense(출력데이터 칸의 수): 출력데이터는 y이고 칸의 수는 1이므로
#Dense(1)

#input_dim: 입력데이터 칸의 수, 입력데이터는 x이고 칸의 수는 2이므로
#Dense(1, input_dim = 2)

#activation = "sigmoid": 선형 회귀 후 sigmoid 함수를 활성 함수로 사용하여 0 ~ 1 사이 값 리턴

#model.add(): Dense 모델을 예측할 수 있도록 model에 추가
model.add(Dense(1, input_dim = 2, activation = "sigmoid"))

In [9]:
#생성된 모델 정보 출력
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [11]:
#Gradient Decent를 이용해서 w, b를 찾는 방법 설정
#loss = 'categorical_crossentropy'
#: sum(-1 / 4 * (y * np.log(hypothesis) + (1 - y) * np.log(1 - hypothesis)))가 최소가 되는 w, b를 찾음
#lr = 0.1: learning_rate를 0.1로 설정
model.compile(loss = 'binary_crossentropy', optimizer = Adam(lr = 0.1), metrics = ['acc'])

In [12]:
#입력값을 X, 출력값을 y로 하여 100번 반복하여 w, b 계산
model.fit(X, y, epochs = 100)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 0.7457 - acc: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 4ms/step - loss: 0.7141 - acc: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6862 - acc: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6613 - acc: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6384 - acc: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6161 - acc: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5942 - acc: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5727 - acc: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 3ms/step - loss: 0.5518 - acc: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5316 - acc: 0.7500
Epoch 11/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5123 -

In [13]:
#X를 예측하여 예측값을 pred에 대입
pred = model.predict(X)
pred

1/1 [==============================] - 0s 46ms/step


array([[0.00204702],
       [0.09809618],
       [0.1166313 ],
       [0.87501377]], dtype=float32)

In [14]:
#pred에 저장된 값이 0.5 초과이면 1, 아니면 0 리턴
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 100)
print("predict01")
print(predict01)

predict01
[[0]
 [0]
 [0]
 [1]]


In [15]:
#predict01을 1차원 배열로 변환
predict02 = predict01.flatten()
predict02

array([0, 0, 0, 1])

In [16]:
#predict02와 y가 같으면 True, 다르면 False 리턴
predict03 = (predict02 == y)
predict03

array([ True,  True,  True,  True])

In [17]:
#True는 1로, False는 0으로 변환하여 합을 계산
np.sum(predict03)

4

In [18]:
#정확도 계산
acc = np.sum(predict03) / 4
acc

1.0

In [19]:
#0, 1의 AND 연산 실행
arr = np.array([[0, 1]], dtype = "float32")

pred = model.predict(arr)
pred

1/1 [==============================] - 0s 14ms/step


array([[0.09809618]], dtype=float32)

In [20]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 100)
print("predict01")
print(predict01)

predict01
[[0]]


In [22]:
#1, 1의 AND 연산 실행
arr = np.array([[1, 1]], dtype = "float32")

pred = model.predict(arr)
pred

1/1 [==============================] - 0s 15ms/step


array([[0.87501377]], dtype=float32)

In [23]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 100)
print("predict01")
print(predict01)

predict01
[[1]]
