In [1]:
!conda install scikit-learn -y

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\anaconda3\envs\tensorflow_env01

  added / updated specs:
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    intel-openmp-2023.1.0      |   h59b6b97_46320         2.7 MB
    mkl-2023.1.0               |   h6b88ed4_46358       155.9 MB
    mkl-service-2.4.0          |  py310h2bbff1b_1          44 KB
    mkl_fft-1.3.10             |  py310h827c3e9_0         181 KB
    mkl_random-1.2.7           |  py310hc64d2fc_0         281 KB
    numpy-1.26.4               |  py310h055cbcc_0          11 KB
    numpy-base-1.26.4          |  py310h65a83cf_0         8.6 MB
    pybind11-abi-5             |       hd3eb1b0_0          14 KB
    scipy-1.13.1               |  py310h8640f81_0        25.4 MB
    tbb-2021.8.0               |       h59b6b97_0    

In [2]:
!conda install pandas -y

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\anaconda3\envs\tensorflow_env01

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numexpr-2.8.7              |  py310h2cd9be0_0         134 KB
    ------------------------------------------------------------
                                           Total:         134 KB

The following NEW packages will be INSTALLED:

  bottleneck         pkgs/main/win-64::bottleneck-1.3.7-py310h9128911_0 
  numexpr            pkgs/main/win-64::numexpr-2.8.7-py310h2cd9be0_0 
  pandas             pkgs/main/win-64::pandas-2.2.2-py310h5da7b33_0 
  python-dateutil    pkgs/main/win-64::python-dateutil-2.9.0post0-py310haa95532_2 
  python-tzdata      pkgs/main/noarch::python-tzdata-2023.3-pyhd3eb1b0_0 
  pytz               pkgs/main/w

In [4]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

In [5]:
#위스콘신 유방암 데이터를 읽어서 data에 저장
data = datasets.load_breast_cancer()

In [6]:
#유방암 판단의 독립변수를 읽어서 X에 저장
X = data.data

#유방암 데이터의 종속 변수(악성: 0, 양성: 1)
y = data.target

In [7]:
#X, y를 8:2로 나누어 훈련 데이터와 테스트 데이터에 대입
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [8]:
from sklearn.preprocessing import StandardScaler

#X에서 평균을 빼고 표준편차로 나누어 평균: 0, 표준편차: 1로 변환할 객체
scaler = StandardScaler()

#X_train의 평균과 표준편차를 계산
scaler.fit(X_train)

StandardScaler()

In [9]:
#X_train에서 평균을 빼고 표준편차로 나누어 X_train에 대입
X_train = scaler.transform(X_train)
X_train

array([[ 4.76684535e-01,  3.42962387e+00,  5.65901446e-01, ...,
         1.35927323e+00,  9.74223596e-01,  1.93879474e+00],
       [-7.78789463e-01, -4.38588577e-02, -8.13853292e-01, ...,
        -6.77912183e-01, -8.26213149e-01, -9.73983742e-01],
       [-1.09117043e+00, -1.07968394e+00, -1.05606729e+00, ...,
        -1.12417930e+00, -7.71163824e-01,  2.24789102e-02],
       ...,
       [-2.31250189e-02, -9.67250271e-01, -7.03428235e-02, ...,
        -2.09231239e-01,  7.23861259e-02, -8.27778339e-01],
       [-1.95678317e-01, -1.06772291e+00, -2.54165947e-01, ...,
        -2.06603411e-01, -1.43013662e+00, -1.20866769e+00],
       [ 6.22462321e-01,  9.60867551e-01,  5.22648947e-01, ...,
        -2.12013646e-01,  6.10524414e-02,  3.05679030e-03]])

In [10]:
#입력값을 읽어 예측할 Sequential 객체 생성
model = Sequential()

#Dense(출력데이터, input_dim=입력데이터, activation="활성함수")
#Dense 모델을 예측할 수 있도록 model에 추가
model.add(Dense(1, input_dim=30, activation="sigmoid"))

In [11]:
#생성된 모델 정보 출력
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [13]:
#Gradient Decent를 이용하여 w와 b를 찾는 방법 설정
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.001), metrics=['acc'])

In [14]:
#입력값을 X, 출력값을 y로 하여 100번 반복해서 w, b 계산
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
15/15 [==============================] - 1s 3ms/step - loss: 0.5251 - acc: 0.7253
Epoch 2/100
15/15 [==============================] - 0s 3ms/step - loss: 0.4608 - acc: 0.7890
Epoch 3/100
15/15 [==============================] - 0s 2ms/step - loss: 0.4073 - acc: 0.8220
Epoch 4/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3676 - acc: 0.8505
Epoch 5/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3352 - acc: 0.8747
Epoch 6/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3103 - acc: 0.8989
Epoch 7/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2889 - acc: 0.9121
Epoch 8/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2717 - acc: 0.9209
Epoch 9/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2568 - acc: 0.9275
Epoch 10/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2445 - acc: 0.9341
Epoch 11/100
15/15 [==============================] - 0s 2m

In [15]:
#scaler를 이용해서 X_test의 범위를 변경
#X_test에서 X_train의 평균을 빼고 X_train의 표준편차로 나눠줌
X_test = scaler.transform(X_test)

In [16]:
pred = model.predict(X_test)

4/4 [==============================] - 0s 1ms/step


In [17]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" *100)
print("predict01")
print(predict01)

predict01
[[1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]]


In [18]:
#predict01을 1차원 배열로 변환
predict02 = predict01.flatten()
predict02

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1])

In [19]:
#predict02와 y_test가 같으면 true, 다르면 false 리턴
predict03 = (predict02 == y_test)
predict03

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [20]:
#true를 1로, false를 0으로 변환하여 합 계산
np.sum(predict03)

111

In [21]:
#len(predict03): redict02의 줄의 수 리턴
len(predict03)

114

In [22]:
#정확도 계산
acc = np.sum(predict03) / len(predict03)
acc

0.9736842105263158