In [1]:
!conda install scikit-learn -y

Channels:
 - defaults
 - nvidia
 - pytorch
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [2]:
!conda install pandas -y

Channels:
 - defaults
 - nvidia
 - pytorch
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import torch
import torch.optim as optim
import torch.nn as nn

In [4]:
#위스콘신 유방암 데이터를 읽어서 data에 저장
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [5]:
#유방암 판단의 독립변수를 읽어서 X에 저장
X = data.data

In [6]:
#유방암 데이터의 종속 변수
#악성이면 0, 양성이면 1
y = data.target

In [7]:
#1차원 배열을 2차원 배열로 변환
y = y.reshape(-1, 1)

In [8]:
#X, y를 8:2로 나누어 80%는 훈련용 데이터로, 20%는 테스트 데이터로 설정
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=778)

In [9]:
from sklearn.preprocessing import StandardScaler

#X에서 평균을 빼고 표준편차로 나눠서 평균: 0, 표준편차: 1로 변환할 객체
scaler = StandardScaler()

#X_train의 평균과 표준편차를 계산
scaler.fit(X_train)

StandardScaler()

In [10]:
#X_train에서 평균을 빼고 표준편차로 나누어 X_train에 대입
X_train = scaler.transform(X_train)
X_train

array([[ 0.14990291,  1.10898417,  0.11541217, ..., -0.67987109,
        -0.60275672, -0.62966586],
       [-0.48116721, -1.51562012, -0.55007951, ..., -1.32531438,
        -0.97405071, -0.74664893],
       [ 1.13448917, -2.09026539,  1.30898459, ...,  2.28468958,
         2.58699616,  1.86239541],
       ...,
       [-0.26204564,  1.39747955, -0.32726241, ..., -0.82224384,
        -0.72242999, -0.87543762],
       [ 0.39531907,  1.09256574,  0.50565919, ...,  1.54180947,
         0.15057116,  1.20771953],
       [-0.73242661, -0.21856367, -0.75936691, ..., -0.47682728,
         0.45282287, -0.29857159]])

In [11]:
#X_test에서 X_train의 평균을 빼고 X_train의 표준편차로 나누어 X_test에 대입
X_test = scaler.transform(X_test)
X_test

array([[-0.45779424, -0.69704381, -0.44776122, ..., -0.45821745,
         0.36843788, -0.47297295],
       [ 1.86197278,  0.50853851,  1.71910335, ...,  0.4554797 ,
        -1.03849016, -0.69352359],
       [-0.59511043, -1.37254518, -0.59235979, ..., -0.61224025,
        -0.2053801 , -0.19715049],
       ...,
       [-0.29126185, -0.87530111, -0.19577073, ...,  1.27400951,
         0.3561637 ,  3.02149367],
       [-0.17439701, -0.09425265, -0.15814127, ...,  0.46758365,
        -0.38182146, -0.39355325],
       [-0.91941035, -0.39212999, -0.89001299, ..., -0.2388333 ,
        -0.96024225, -0.07587447]])

In [12]:
#유방암 데이터를 계산하기 위한 w 생성
#torch.empty(30, 1): 30행 1열의 tensor 배열 리턴
w = torch.empty(30, 1)
w

tensor([[-8.6784e-19],
        [ 8.9683e-43],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00]])

In [13]:
#w를 어떻게 초기화해야 빠르게 cost가 0에 수렴하는가?
#참고: https://www.youtube.com/watch?v=4rC0sWrp3Uw
#w에 학습이 잘되도록 값을 대입(xavier initialization)

w = torch.nn.init.xavier_uniform_(w)
w

tensor([[-0.4080],
        [-0.0414],
        [ 0.2634],
        [-0.1662],
        [ 0.3745],
        [-0.2526],
        [ 0.0882],
        [ 0.1147],
        [ 0.0383],
        [-0.0756],
        [-0.0158],
        [-0.0071],
        [ 0.3712],
        [ 0.0911],
        [ 0.3617],
        [-0.0270],
        [ 0.2358],
        [-0.2102],
        [-0.2852],
        [-0.4146],
        [-0.1412],
        [-0.2717],
        [-0.3318],
        [ 0.0795],
        [ 0.3689],
        [-0.2191],
        [ 0.3045],
        [-0.2887],
        [ 0.2930],
        [-0.2561]])

In [14]:
#곱해지는 값 w를 초기화
#학습을 통해 값이 변경되는 변수임을 명시(requires_grad = True)
w = torch.tensor(w, requires_grad = True)
w

C:\Users\User\AppData\Local\Temp\ipykernel_18204\3206577545.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  w = torch.tensor(w, requires_grad = True)


tensor([[-0.4080],
        [-0.0414],
        [ 0.2634],
        [-0.1662],
        [ 0.3745],
        [-0.2526],
        [ 0.0882],
        [ 0.1147],
        [ 0.0383],
        [-0.0756],
        [-0.0158],
        [-0.0071],
        [ 0.3712],
        [ 0.0911],
        [ 0.3617],
        [-0.0270],
        [ 0.2358],
        [-0.2102],
        [-0.2852],
        [-0.4146],
        [-0.1412],
        [-0.2717],
        [-0.3318],
        [ 0.0795],
        [ 0.3689],
        [-0.2191],
        [ 0.3045],
        [-0.2887],
        [ 0.2930],
        [-0.2561]], requires_grad=True)

In [15]:
#더해지는 값 b는 0으로 초기화(torch.tensor([0.0])
#학습을 통해 값이 변경되는 변수임을 명시(requires_grad = True)
b = torch.tensor([0.0], requires_grad = True)
b

tensor([0.], requires_grad=True)

In [16]:
#X_train을 float 타입 tensor로 변환
X_train = torch.FloatTensor(X_train)
X_train

tensor([[ 0.1499,  1.1090,  0.1154,  ..., -0.6799, -0.6028, -0.6297],
        [-0.4812, -1.5156, -0.5501,  ..., -1.3253, -0.9741, -0.7466],
        [ 1.1345, -2.0903,  1.3090,  ...,  2.2847,  2.5870,  1.8624],
        ...,
        [-0.2620,  1.3975, -0.3273,  ..., -0.8222, -0.7224, -0.8754],
        [ 0.3953,  1.0926,  0.5057,  ...,  1.5418,  0.1506,  1.2077],
        [-0.7324, -0.2186, -0.7594,  ..., -0.4768,  0.4528, -0.2986]])

In [17]:
#X_test를 float 타입 tensor로 변환
X_test = torch.FloatTensor(X_test)
X_test

tensor([[-0.4578, -0.6970, -0.4478,  ..., -0.4582,  0.3684, -0.4730],
        [ 1.8620,  0.5085,  1.7191,  ...,  0.4555, -1.0385, -0.6935],
        [-0.5951, -1.3725, -0.5924,  ..., -0.6122, -0.2054, -0.1972],
        ...,
        [-0.2913, -0.8753, -0.1958,  ...,  1.2740,  0.3562,  3.0215],
        [-0.1744, -0.0943, -0.1581,  ...,  0.4676, -0.3818, -0.3936],
        [-0.9194, -0.3921, -0.8900,  ..., -0.2388, -0.9602, -0.0759]])

In [18]:
#y_train을 float 타입 tensor로 변환
y_train = torch.FloatTensor(y_train)
y_train

tensor([[1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
      

In [19]:
#y_test를 float 타입 tensor로 변환
y_test = torch.FloatTensor(y_test)
y_test

tensor([[1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [20]:
#배열 X_train과 w를 곱하고 b를 더한 값을 시그모이드를 이용하여 0 ~ 1사이 값 리턴
hypothesis = torch.sigmoid(torch.matmul(X_train, w) + b)
hypothesis

tensor([[0.2780],
        [0.4313],
        [0.5603],
        [0.3216],
        [0.7529],
        [0.4266],
        [0.3056],
        [0.5248],
        [0.4368],
        [0.4343],
        [0.8130],
        [0.6392],
        [0.5042],
        [0.0625],
        [0.6469],
        [0.1290],
        [0.7687],
        [0.2450],
        [0.1630],
        [0.1546],
        [0.6210],
        [0.6886],
        [0.8019],
        [0.4954],
        [0.7717],
        [0.3033],
        [0.5016],
        [0.6973],
        [0.4468],
        [0.8108],
        [0.9118],
        [0.4149],
        [0.7141],
        [0.4732],
        [0.5468],
        [0.4473],
        [0.4083],
        [0.3999],
        [0.1210],
        [0.3840],
        [0.7478],
        [0.7231],
        [0.5740],
        [0.4465],
        [0.7397],
        [0.1505],
        [0.3179],
        [0.6089],
        [0.5856],
        [0.5808],
        [0.6090],
        [0.0402],
        [0.3348],
        [0.9311],
        [0.8302],
        [0

In [21]:
#미분을 자동 계산해서 w, b를 수정할 객체 생성
#learning_rate는 0.01로 설정
optimizer = optim.Adam([w, b], lr = 0.01)

In [22]:
#반복하여 w, b를 찾음
for i in range(100):
    print("i=", i)
    print("w=", w[:3])
    print("b=", b)

    #리턴값이 0.5 미만은 0(악성), 0.5 이상은 1(양성)으로 분류
    hypothesis = torch.sigmoid(torch.matmul(X_train, w) + b)

    #오차를 계산해서 cost에 저장
    cost = torch.mean(-y_train * torch.log(hypothesis) - (1 - y_train) * torch.log(1 - hypothesis))
    print("cost=", cost)

    #cost를 이용하여 미분을 계산하고 w, b 업데이트
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    print("=" * 100)

i= 0
w= tensor([[-0.4080],
        [-0.0414],
        [ 0.2634]], grad_fn=<SliceBackward0>)
b= tensor([0.], requires_grad=True)
cost= tensor(0.6527, grad_fn=<MeanBackward0>)
i= 1
w= tensor([[-0.4180],
        [-0.0514],
        [ 0.2534]], grad_fn=<SliceBackward0>)
b= tensor([0.0100], requires_grad=True)
cost= tensor(0.5978, grad_fn=<MeanBackward0>)
i= 2
w= tensor([[-0.4280],
        [-0.0614],
        [ 0.2434]], grad_fn=<SliceBackward0>)
b= tensor([0.0200], requires_grad=True)
cost= tensor(0.5494, grad_fn=<MeanBackward0>)
i= 3
w= tensor([[-0.4379],
        [-0.0713],
        [ 0.2335]], grad_fn=<SliceBackward0>)
b= tensor([0.0300], requires_grad=True)
cost= tensor(0.5071, grad_fn=<MeanBackward0>)
i= 4
w= tensor([[-0.4477],
        [-0.0811],
        [ 0.2237]], grad_fn=<SliceBackward0>)
b= tensor([0.0399], requires_grad=True)
cost= tensor(0.4701, grad_fn=<MeanBackward0>)
i= 5
w= tensor([[-0.4574],
        [-0.0907],
        [ 0.2141]], grad_fn=<SliceBackward0>)
b= tensor([0.0498], re

In [23]:
predict = torch.sigmoid(torch.matmul(X_test, w) + b)
predict

tensor([[9.7549e-01],
        [2.8698e-03],
        [9.9624e-01],
        [9.8876e-01],
        [9.9531e-01],
        [9.4487e-01],
        [4.1872e-02],
        [1.8481e-01],
        [1.0132e-07],
        [9.9837e-01],
        [9.4996e-01],
        [9.9935e-01],
        [1.2367e-03],
        [8.5746e-01],
        [7.3909e-06],
        [6.3315e-01],
        [1.9548e-02],
        [9.8079e-01],
        [8.8045e-01],
        [9.9265e-01],
        [2.8408e-07],
        [1.1884e-07],
        [9.7660e-01],
        [6.0178e-03],
        [7.8836e-01],
        [8.9105e-01],
        [9.1999e-01],
        [9.6206e-03],
        [5.8337e-01],
        [9.6045e-01],
        [1.6701e-02],
        [9.6629e-01],
        [7.2700e-01],
        [5.5087e-03],
        [5.0356e-03],
        [3.2857e-04],
        [1.2930e-02],
        [9.9373e-01],
        [5.6000e-04],
        [8.6540e-01],
        [1.4513e-04],
        [9.6744e-01],
        [1.1252e-03],
        [8.0009e-01],
        [8.5079e-01],
        [9

In [24]:
#predict가 0.5 이상이면 1(양성), 미만이면 0(악성) 리턴
predict01 = torch.where(predict >= 0.5, torch.tensor([1.]), torch.tensor([0.]))
predict01

tensor([[1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [25]:
#실제 유방암 결과(y_test)와 예측값(predict01)이 같으면 True, 다르면 False 리턴
acc01 = predict01.eq(y_test)

In [26]:
#acc01에 저장된 값이 True면 1, False라면 0으로 변환
acc02 = acc01.type(torch.DoubleTensor)
acc02

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [27]:
#acc02에 저장된 값을 모두 더한 후 전체 데이터 수로 나눔(평균을 구함)
acc03 = torch.mean(acc02)
acc03

tensor(0.9649, dtype=torch.float64)

In [28]:
#악성 암인지 양성 암인지 알고 싶은 환자의 유방암 정보
X_arr = np.array([
        [3.8312, 1.6324, 3.9907, 5.4532, 0.8753, 1.8759,
         3.5362, 3.1806, 0.8990,-0.9087, 7.9715, 0.1713,
         8.0943,11.9829, 0.2529, 1.6661, 1.5853, 2.3802,
        -0.4427, 0.3207, 4.1694, 0.9339, 4.3981, 6.2228,
         0.1643, 1.1448, 1.9777, 2.2735,-0.4414,-0.5454]
    ])
X_arr

array([[ 3.8312,  1.6324,  3.9907,  5.4532,  0.8753,  1.8759,  3.5362,
         3.1806,  0.899 , -0.9087,  7.9715,  0.1713,  8.0943, 11.9829,
         0.2529,  1.6661,  1.5853,  2.3802, -0.4427,  0.3207,  4.1694,
         0.9339,  4.3981,  6.2228,  0.1643,  1.1448,  1.9777,  2.2735,
        -0.4414, -0.5454]])

In [31]:
#X_arr을 학습데이터의 평균을 빼고 표준편차로 나눔
X_arr = scaler.transform(X_arr)
X_arr

array([[-4.99862879e+00, -5.49638886e+00, -4.04007624e+00,
        -1.93383066e+00,  3.94161972e+03,  5.98363271e+02,
         5.14884115e+02,  2.05218142e+03,  8.76334437e+02,
        -1.98131337e+04,  1.11085273e+02, -5.60870550e+00,
        -8.91853127e-03, -9.70534532e-01,  2.62148177e+04,
         4.85940161e+03,  1.48001143e+03,  6.12079815e+04,
        -6.37944936e+03,  4.59578113e+04, -3.97654096e+00,
        -4.84283721e+00, -3.34450931e+00, -1.58351141e+00,
         5.58779984e+01,  3.10155754e+01,  3.47295550e+01,
         4.92520893e+02, -1.76993046e+02, -1.81750031e+03]])

In [32]:
#X_arr을 tensor 객체로 변환
X_arr = torch.FloatTensor(X_arr)
X_arr

tensor([[-4.9986e+00, -5.4964e+00, -4.0401e+00, -1.9338e+00,  3.9416e+03,
          5.9836e+02,  5.1488e+02,  2.0522e+03,  8.7633e+02, -1.9813e+04,
          1.1109e+02, -5.6087e+00, -8.9185e-03, -9.7053e-01,  2.6215e+04,
          4.8594e+03,  1.4800e+03,  6.1208e+04, -6.3794e+03,  4.5958e+04,
         -3.9765e+00, -4.8428e+00, -3.3445e+00, -1.5835e+00,  5.5878e+01,
          3.1016e+01,  3.4730e+01,  4.9252e+02, -1.7699e+02, -1.8175e+03]])

In [33]:
#양성인지 악성인지 판별
torch.sigmoid(torch.matmul(X_arr, w) + b)

tensor([[0.]], grad_fn=<SigmoidBackward0>)